version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Etc/UTC
    labels:
      - 'type: improvement'
      - 'scope: inventory'
      - 'scope: deps'
    commit-message:
      prefix: 'ci/cd'
      include: 'scope'
    open-pull-requests-limit: 30

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '05:00'
      timezone: Etc/UTC
    labels:
      - 'type: feature'
      - 'scope: code'
      - 'scope: deps'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
    open-pull-requests-limit: 30

  - package-ecosystem: npm
    directory: /tools/
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Etc/UTC
    labels:
      - 'type: improvement'
      - 'scope: inventory'
      - 'scope: deps'
    commit-message:
      prefix: 'tools'
      include: 'scope'
    open-pull-requests-limit: 30
