name: Delivery to Cloudflare Pages

on:
  schedule:
    - cron: 0 7 1 * * # at 07:00 on day-of-month 1, UTC

  workflow_dispatch:
    inputs:
      reason:
        description: The reason for dispatching it manually.
        type: string
        default: manual healthcheck
        required: true

  workflow_run:
    workflows: [ Continuous integration ]
    types: [ completed ]
    branches: [ main ]

concurrency:
  group: cloudflare-pages
  cancel-in-progress: true

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    if: ${{ contains(fromJSON('[null, "success"]'), github.event.workflow_run.conclusion) }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1
        with: { fetch-depth: 0 }
      - name: Set up Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
          check-latest: true
      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build
      - name: Upload the site
        uses: actions/upload-artifact@v3.1.3
        with: { name: dist, path: dist/, if-no-files-found: error }

  deploy:
    name: Deploying
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: cloudflare-pages
      url: ${{ steps.deployment.outputs.url }}

    steps:
      - name: Fetch the site
        uses: actions/download-artifact@v3.0.2
        with: { name: dist, path: dist/ }

      - name: Publish it to Cloudflare Pages
        id: deployment
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT }}
          directory: dist
          wranglerVersion: 3

  notify:
    name: Notifying
    needs: [ build, deploy ]
    runs-on: ubuntu-latest
    if: failure() || success()

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1
        with: { fetch-depth: 0 }

      - name: Send notification
        uses: ./.github/actions/notify
        continue-on-error: true
        with:
          emoji: 🚀
          channel: ${{ secrets.SLACK_WEBHOOK }}
          success: ${{ ! contains(needs.*.result, 'failure') }}
